spring:
  application:
    name: 14th-BeneFitU-Backend

  # [1] 데이터베이스 연동 설정 (도커 컴포즈 'mysql' 서비스 명세와 연동)
  datasource:
    url: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # [2] ORM 설정
  jpa:
    open-in-view: false  # 트래픽 처리를 위해 영속성 컨텍스트 범위를 서비스 레이어로 제한 (매우 훌륭함)
    hibernate:
      ddl-auto: update   # 로컬/해커톤 개발용 (운영서버 배포 시에는 가급적 none 이나 validate 권장)
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# [3] JWT 설정
jwt:
  secret: ${JWT_SECRET_KEY}

# [4] 스웨거 문서 설정 (오타 수정 완료)
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

# 2026.7.7 이후 설정들
# [5] 공공 api 키 설정
api:
  youth-center:
    key: ${YOUTH_CENTER_API_KEY:default_key} # 환경 변수가 없으면 default_key 사용

logging:
  level:
    org.springframework.security: DEBUG